// <auto-generated />
using System;
using Fitness.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fitness.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240516022304_addImageUrlToDietsDb")]
    partial class addImageUrlToDietsDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fitness.Models.Diets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryDietId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DietName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kcal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryDietId");

                    b.ToTable("Diets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryDietId = 1,
                            Description = "Dieta numer 1",
                            DietName = "Dieta 1500kcal",
                            ImageUrl = "",
                            Kcal = 1500
                        },
                        new
                        {
                            Id = 2,
                            CategoryDietId = 2,
                            Description = "Dieta numer 2",
                            DietName = "Dieta 2000kcal",
                            ImageUrl = "",
                            Kcal = 1500
                        },
                        new
                        {
                            Id = 3,
                            CategoryDietId = 1,
                            Description = "Dieta numer 3",
                            DietName = "Dieta 2500kcal",
                            ImageUrl = "",
                            Kcal = 1500
                        },
                        new
                        {
                            Id = 4,
                            CategoryDietId = 3,
                            Description = "Dieta numer 3",
                            DietName = "Dieta 3000kcal",
                            ImageUrl = "",
                            Kcal = 1500
                        },
                        new
                        {
                            Id = 5,
                            CategoryDietId = 2,
                            Description = "Dieta numer 3",
                            DietName = "Dieta 3500kcal",
                            ImageUrl = "",
                            Kcal = 1500
                        },
                        new
                        {
                            Id = 6,
                            CategoryDietId = 3,
                            Description = "Dieta numer 3",
                            DietName = "Dieta 4000kcal",
                            ImageUrl = "",
                            Kcal = 1500
                        });
                });

            modelBuilder.Entity("Fitness.Models.DietsCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisplayOrder")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DietsCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Dieta Ketogeniczna",
                            DisplayOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Dieta Wysokobiałkowa",
                            DisplayOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Dieta Wegańska",
                            DisplayOrder = 3
                        });
                });

            modelBuilder.Entity("Fitness.Models.Diets", b =>
                {
                    b.HasOne("Fitness.Models.DietsCategory", "DietsCategory")
                        .WithMany()
                        .HasForeignKey("CategoryDietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietsCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
